### ISSUE TITLE
rebuild index from scratch with Jubilee considerations

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/ordinals-api#294]
We should rebuild an ordhook index completely which follows the new rules set by Jubilee after its activation block height and which recognizes all the cursed inscriptions we've been missing lately. We should then create a new API ingestion from it and upload it to our Hiro archives.

This will fix https://github.com/hirosystems/ordinals-api/issues/192

**Comment by 0xbitfly** [comment]
any progress? I have checked the pg archives , it's doesn't change since 2023-12-18
![image](https://github.com/hirosystems/ordinals-api/assets/96873065/79249d82-bf89-410a-9af6-f7040dd32154)

**Comment by rafaelcr** [comment]
@0xbitfly apologies for the delay. We've had to restart the index from some issues that were identified in the `ord` codebase. I'll update this thread as soon as we have some progress.

**Comment by 314159265359879** [comment]
I saw issues with indexing on old inscriptions mostly. Now it looks like there are more cases popping up with recent inscriptions not getting their owner updated. Is this still related and will be resolved with this fix?

Example this wallet
bc1pta02pkqhs5peckkfu6engydug54hcu8rwqkszga07x3l99n8shjqlj86k0

on [ord.io](https://www.ord.io/bc1pta02pkqhs5peckkfu6engydug54hcu8rwqkszga07x3l99n8shjqlj86k0):
![image](https://github.com/leather-wallet/extension/assets/33360391/e938a552-33a3-4b0d-a3c1-f15b26d596b6)

on [ordinals.hiro.so](https://ordinals.hiro.so/address/bc1pta02pkqhs5peckkfu6engydug54hcu8rwqkszga07x3l99n8shjqlj86k0):
![image](https://github.com/leather-wallet/extension/assets/33360391/cbd64b3f-cd7a-429e-bab2-c96cdc1bf43b)

This inscription for example is still displayed as owned by the inscriber instead of the new address (same with the other three).
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/617ea0e3-8554-4071-a803-a666a2bae997)

**Comment by rafaelcr** [comment]
The indexing is now complete and all traffic has been switched to API v3.0.0. Thanks again for everybody's patience! We appreciate it.
