### ISSUE TITLE
Optimize COUNT queries on /ordinals/inscriptions

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/ordinals-api#79]
Any COUNT queries invoked by calls to `/ordinals/inscriptions` can be resource heavy on the backend database, often leading to cyclic locks, rapidly growing tmp files, no disk space, and thus HTTP 500s/downtime.
To handle this in the past, caches have been introduced in the db for common queries to this endpoint to reduce db load. However this may not be suitable for the longterm since there is no finite number of paths on the `/ordinals/inscriptions` endpoint.

We should look into optimizing all COUNT queries across the board in a way that doesn't require revisiting and adding more caches in the future.

**Comment by sabbyanandan** [comment]
@rafaelcr: Given the lack of "totals" in the response payload breaking the pagination behavior for a few Dapps, I would request to bump the priority on this one. Let's get this sorted out.

**Comment by chresko** [comment]
What would an optimized COUNT query look like?

**Comment by rafaelcr** [comment]
@chresko the idea is to pre-cache the counts for various filters available via the `/inscriptions` endpoint so we can load those totals instead of calculating COUNT queries on demand (which are very expensive to do).

We already have some of this work in place for the most used filters (address, mime type, etc.) but we need to add others for more arbitrary filters.

**Comment by rafaelcr** [comment]
Small regression was found that duplicates some counts on block replays, I'll fix that

**Comment by rafaelcr** [comment]
This is now fixed
